/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StinkySkunk12 (https://sketchfab.com/Bearfnf)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/big-boo-super-mario-world-custom-46f17f7605c04add9aa310b575335a2b
Title: Big Boo Super Mario World (Custom)
*/

import { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useMotionValue, useSpring } from "motion/react";

export function Ghost({ isMobile }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/big_boo_super_mario_world_custom.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(12); // ✅ starts way above screen
  const ySpring = useSpring(yPosition, {
    damping: 8, // ✅ low damping = bouncy/overshoots — feels alive
    stiffness: 60, // lower = slower dramatic drop
    mass: 1.2, // slight weight to the fall
  });

  useFrame(() => {
    group.current.position.y = ySpring.get();
  });

  useEffect(() => {
    // ✅ Small delay so it doesn't fire before scene loads
    const timeout = setTimeout(() => {
      yPosition.set(-1); // final resting position
    }, 300);

    return () => clearTimeout(timeout);
  }, [yPosition]);

  useFrame(({ clock }) => {
    if (!group.current) return;
    const t = clock.getElapsedTime();

    // Target per viewport
    const targetX = isMobile ? 0 : 2.5; // center on mobile, right on desktop
    const targetY = isMobile ? 20 : 20; // vertically centered both
    const targetZ = isMobile ? 0 : 0;
    const targetScale = isMobile ? 0.7 : 1;
    const targetRotZ = isMobile ? 0 : -0.6; // 0.6 = faces lower-left on desktop

    const lerp = (a, b, s) => a + (b - a) * s;
    const s = 0.04;

    // Smooth transition between viewports
    group.current.position.x = lerp(group.current.position.x, targetX + Math.sin(t * 0.4) * 0.05, s);
    group.current.position.y = lerp(group.current.position.y, targetY + Math.sin(t * 0.8) * 0.15, s);
    group.current.position.z = lerp(group.current.position.z, targetZ, s);

    const sc = lerp(group.current.scale.x, targetScale, s);
    group.current.scale.set(sc, sc, sc);

    // Facing direction + gentle wobble
    group.current.rotation.z = lerp(group.current.rotation.z, targetRotZ + Math.sin(t * 0.5) * 0.06, s);
  });

  return (
    // Only X is fixed here (GLTF upright), everything else owned by useFrame
    <group ref={group} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <group>
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Big_Bioo_Body} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Big_Bioo_Body_0} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.Big_Bioo_Body_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.Big_Bioo_Body_2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.Big_Bioo_Body_2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.Big_Bioo_Body_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Big_Bioo_Body_0} />
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.Big_Bioo_Body} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/big_boo_super_mario_world_custom.glb");
